//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="TAL.Common")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="TAL.Common", IsNullable=false)]
public partial class CanonicalEvent {
    
    private CanonicalEventEventInfo eventInfoField;
    
    private CanonicalEventEventData eventDataField;
    
    /// <remarks/>
    public CanonicalEventEventInfo EventInfo {
        get {
            return this.eventInfoField;
        }
        set {
            this.eventInfoField = value;
        }
    }
    
    /// <remarks/>
    public CanonicalEventEventData EventData {
        get {
            return this.eventDataField;
        }
        set {
            this.eventDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="TAL.Common")]
public partial class CanonicalEventEventInfo {
    
    private string processNameField;
    
    private string trackingIdField;
    
    private string referenceNumberField;
    
    private string senderField;
    
    private System.DateTime dateField;
    
    private bool dateFieldSpecified;
    
    private string typeField;
    
    /// <remarks/>
    public string ProcessName {
        get {
            return this.processNameField;
        }
        set {
            this.processNameField = value;
        }
    }
    
    /// <remarks/>
    public string TrackingId {
        get {
            return this.trackingIdField;
        }
        set {
            this.trackingIdField = value;
        }
    }
    
    /// <remarks/>
    public string ReferenceNumber {
        get {
            return this.referenceNumberField;
        }
        set {
            this.referenceNumberField = value;
        }
    }
    
    /// <remarks/>
    public string Sender {
        get {
            return this.senderField;
        }
        set {
            this.senderField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime Date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DateSpecified {
        get {
            return this.dateFieldSpecified;
        }
        set {
            this.dateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="TAL.Common")]
public partial class CanonicalEventEventData {
    
    private CanonicalEventEventDataProperty[] propertiesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Property", IsNullable=false)]
    public CanonicalEventEventDataProperty[] Properties {
        get {
            return this.propertiesField;
        }
        set {
            this.propertiesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="TAL.Common")]
public partial class CanonicalEventEventDataProperty {
    
    private string nameField;
    
    private CanonicalEventEventDataPropertyValue valueField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public CanonicalEventEventDataPropertyValue Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="TAL.Common")]
public partial class CanonicalEventEventDataPropertyValue {
    
    private System.Xml.XmlNode[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlNode[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
}
